### ISSUE TITLE
Configure mob spawning and loot

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#2]

**Comment by GnarlyOldGuy** [comment]
Is there a mid-level meat-type defined in Animania or Better Animals Plus, or am I being a little too analytical on this config?  Assigning chevon to the small mammal loot seems out of place since it is a specific meat-type from lamb.  Something like a small steak?

**Comment by tungstonminer** [comment]
Unfortunately, I don't think there is.  We can re-name things, so they aren't so specific to a particular animal, and we can control *how many* items are dropped.  We also have "Ground *meat*" items we can use.  Between those things, I think we could devise a scale from "a single slice of meat" to "a pile of steaks" to suit the various animals.  What we really want is to make sure things are reasonably scaled to the size of the creature.

**Comment by GnarlyOldGuy** [comment]
Notes on mob spawns and loot drops

1. Minecraft cow - I think we should exclude this one from spawning, we have much more robust bovine examples with Animania
2. Minecraft chicken - Ditto
3. Minecraft pig - Ditto
4. Minecraft rabbit - Ditto
5. Minecraft sheep - Ditto
6. Minecraft wolf - I think we could exclude this one from spawning, we have a much better and potentially challenging version through Better Animals Plus.
7. Also, I think the default drops on some of the mobs are pretty balanced, for instance, the Feral Wolf is a random spawn type and the drop is a wolf pelt that matches the wolf, but also an occasional Wold Head that matches.

The Group Size Presets - is this limiting within a certain area for the mob type?  Just curious because of how I am building the spawn right now.  For instance, I set all the bovine to CLUSTER, so there could potentially be a rather large grouping of those types in a biome.  It made sense to me from a herding perspective, but maybe it would be too many animals?

I'm over halfway through the list right now and making OK progress.  It's mostly the ones and twos now.

**Comment by tungstonminer** [comment]
I agree with everything to do with the vanilla animals except the wolf.  My impression was that you *can't* tame the feral wolk to dogs, and I think some players would like to keep that option.  So, I'd say to keep both the vanilla Wolf and the Feral Wolf from BetterAnimalsPlus.

For any animals where you think the default drops are fine, then I'd say to just use the `use_default` loot table, and let things be.  I think this goes especially for the Feral Wolves because of the color-matching issue which would be difficult (if not impossible) to replicate.

The group size is how many animals should appear as part of the same mob spawn event.  The other values control how many there can be altogether.  Obviously, you want to have the total capacity for a certain animal to be at least as large as one group.  If not, it could actually prevent from the mob from spawning at all.

Excellent progress so far!  This is definitely one of the hardest part of configuring a modpack!  One thing to consider... what settings do you think we should have for aggressive, hostile mobs?  We could simply go with the Ad Astra settings, but this is a good opportunity to consider whether we liked they way that worked and to change things, if we prefer something else.

**Comment by GnarlyOldGuy** [comment]
Feral Wolves can be tamed, but you need to be wearing the Ender Dragon Head to make it happen.  I'll leave the regular wolf in.

I was doing some reading on the Better Animals Plus mod site, so I will have a better feeling for this after I get more info.  It seems the Feral Wolves are very aggressive by nature in the original mod configuration.  I'll check the others.

**Comment by GnarlyOldGuy** [comment]
After reading the info on the Better Animals web site, I think we should leave the hostile mobs with their default settings from the mod.
Take a look, [https://better-animals-plus.fandom.com/wiki/Creatures](url)

**Comment by tungstonminer** [comment]
When you say "default settings", do you mean just drops, or everything (i.e., spawn location, etc.).  From what I've scanned briefly, it seems like the Feral Wolves are the only ones which really *require* us to leave the loot tables alone, while the rest are really more up to us whether we want to bother.  My input would be to stick with the defaults for any animal which feels reasonably balanced against the others.

**Comment by GnarlyOldGuy** [comment]
I was actually talking about the aggression idea you were talking about above.
I think the loot drops were pretty balanced as well, but I only looked at the hostile mobs in detail.  Maybe a couple of tweaks here or there, my concern is changing their loot tables to something we craft may introduce more frequent drops for things like heads which have a roughly 8 percent drop chance right now I believe.

**Comment by tungstonminer** [comment]
Ah... I see.  I was thinking about the "where" and "how many" part of things, which I think we'll definitely want to re-balance along side all the many other creatures which will be present.  So, for example, where to bears live?  How common are they?  What about Moose, or wolves?  No need to have an answer quite yet, but that will definitely be something we need to solve fairly soon.

**Comment by GnarlyOldGuy** [comment]
About the where and how many, that may be something we want to sit down and chat about.  I think we are probably pretty much on the same page.  For instance, do we want horses spawning in the desert, savanna, and mesa areas?  Wild horses exist in the desert Southwest, so should we include that in the mod pack?  What others may we want to replicate as closely as possible?  I think we may want to look at overlap as well and if that may be an issue, for instance, polar bears and the other bears, do we care if there is overlap there or not a big issue.  Personally, not a big deal for me.

**Comment by tungstonminer** [comment]
@GnarlyOldGuy got all the hard work done of getting everything in the right place.  I'll take over from this point to re-generate the config files and get them included into the modpack.
