### ISSUE TITLE
Immersive Petroleum distillation tower not consuming power to operate

### ISSUE THREAD

**Issue by spunkiethefirst** [tungstonminer/brunel-3#249]
The immersive petroleum distillation tower does not consume power when producing ethanol from forestry biomass nor when processing crude oil.

Loaded 2 distillation towers, 24 buckets of crude in one and 24 buckets of biomass in the other, and charged their power buffers to full 16000  using a creative capacitor. The capacitor was then removed and the towers turned on to process.

Was able to process 24 buckets of ethanol and crude without the energy buffer of the tower decreasing in either instance.

**Comment by tungstonminer** [comment]
I've been able to reproduce your results, but I'm totally baffled as to what's going on.  The best guess I have at the moment is that there's something broken about the I.P. / CraftTweaker integration which causes any recipes created by CraftTweaker to be lacking the power input.  More investigation to follow...

**Comment by tungstonminer** [comment]
Turns out there was a [documentation error](https://github.com/CraftTweaker/CraftTweaker-Documentation/pull/436) in the CraftTweaker docs.  It indicated that the power requirement should be specified as "flux/t" instead of "total flux".  Obviously, the former requires a very tiny number while the latter requires quite a large number.  I'll update the recipes to reflect this.

**Comment by tungstonminer** [comment]
I've updated the scripts to use the correct version of the API.
