### ISSUE TITLE
We have far too many Beehives in the current configuration.

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/brunel-3#33]

**Comment by tungstonminer** [comment]
Agreed.  As a general principle on resources, I try to arrange things so that players should have to spend approximately one Minecraft day looking for a resource once they've gotten themselves to the right biome.  Common items (like beehives) should be maybe half that, and rare items (like gemstones) perhaps double.

**Comment by tungstonminer** [comment]
I've reduced these to a quarter of the default spawn rate.  Feels about right to me.
